name: Section9 - custom actions - composite
on:
  push:
    branches:
      - main
    paths:
      - '**/section9-demo/**'
      - '**/workflows/section9-demo.yml'
      - '**/actions/cached-deps/action.yml'
      - '**/actions/deploy-s3-javascript/action.yml'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      # - name: Cache dependencies
      #   id: cache
      #   uses: actions/cache@v3
      #   with:
      #     path: node_modules
      #     key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      # - name: Install dependencies
      #   if: steps.cache.outputs.cache-hit != 'true'
      #   run: |
      #     cd section9-demo
      #     npm ci
      - name: Load & cache dependencies
        id: cache-step
        uses: ./.github/actions/cached-deps #using custom action instead of the manual steps defined above
        with:
          package-lock-file-path: 'section9-demo'
          caching: 'false'
      - name: Output info
        run: echo "Cache used? ${{ steps.cache-step.outputs.used-cache }}"
      - name: Lint code
        run: |
          cd section9-demo
          npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
        with:
          package-lock-file-path: 'section9-demo'
      - name: Test code
        id: run-tests
        run: |
          cd section9-demo
          npm run test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
        with:
          package-lock-file-path: 'section9-demo'
      - name: Build website
        run: |
          cd section9-demo
          npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: section9-demo/dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Get build artifacts
        uses: actions/download-artifact@v5
        with:
          name: dist-files
          path: ./dist
      - name: Output contents
        run: ls
      - name: Deploy site
        id: deploy
        #run: echo "Deploying..."
        uses: ./.github/actions/deploy-s3-javascript
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          bucket: bucket_name
          dist-folder: ./dist
      - name: Output info
        run: |
          echo "Live URL: ${{ steps.deploy.outputs.website-url }}"
  # information:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Get code
  #       uses: actions/checkout@v3 #this is required, as the custom javascript action is defined in our own repository
  #     - name: Run custom javascript action
  #       uses: ./.github/actions/deploy-s3-javascript