name: Deployment
on:
  push:
    branches:
      - main
      - dev
    paths:
      - '**/section6-demo/**'
      - '**/workflows/section6-demo.yml'
env:
  MONGODB_DB_NAME: gha-demo
jobs:
  test:
    env:
      MONGODB_CLUSTER_ADDRESS: test.db.address
      MONGODB_USERNAME: test_user
      MONGODB_PASSWORD: test_pwd
      PORT: 
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: |
          cd section6-demo
          npm ci
      - name: Run server
        run: |
          cd section6-demo
          npm start & npx wait-on http://127.0.0.1:$PORT #interpolates the env var into the string. windows would be like $env:NAME
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
      - name: Run tests
        run: |
          cd section6-demo
          npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
          echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
