name: Section7 - Reusable Deploy
on:
    workflow_call:
        inputs:
          artifact-name:
            description: The name of the deployable artifact files
            required: false
            default: dist
            type: string
        # secrets:
        #     some-secret:
        #         required: true
        outputs:
            result:
                description: The result of the deployment process
                value: ${{ jobs.deploy.outputs.outcome }}
jobs:
    deploy:
        outputs:
          outcome: ${{ steps.set-result.outputs.operation_result }}
        runs-on: ubuntu-latest
        steps:
            - name: Get artifacts
              uses: actions/download-artifact@v5
              with:
                name: ${{ inputs.artifact-name }}
            - name: list files
              run: ls
            - name: Output information
              run: echo "Deploying & uploading..."
            - name: Set result output
              id: set-result
              run: echo 'operation_result=sucess' >> $GITHUB_OUTPUT