name: Deploy website
on:
  push:
    branches:
      - main
    paths:
      - '**/section5-demo/**'
      - '**/workflows/section5-demo.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd section5-demo
          npm ci
      - name: Lint code
        run: |
          cd section5-demo
          npm run lint
      - name: Test code
        run: |
          cd section5-demo
          npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.file_name }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd section5-demo
          npm ci
      - name: Build website
        run: |
          cd section5-demo
          npm run build
      - name: Publish JS filename
        id: publish
        run: find section5-demo/dist/assets/*.js -type f -execdir echo 'file_name={}' >> $GITHUB_OUTPUT ';'
        #run: find section5-demo/dist/assets/*.js -type f -execdir echo '::set-output name=file_name::{}' ';' -> alternative that does the same thing, but will be removed
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: section5-demo/dist
          # path: |
          #   section5-demo/dist
          #   section5-demo/package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v5
        with:
          name: dist-files
      - name: Output contents
        run: ls
      - name: Output filename
        run: echo "${{ needs.build.outputs.script-file }}"
      - name: Deploy
        run: echo "Deploying..."
